#%RAML 1.0 DataType

type: object
displayName: Child Parent Site Mapping
properties:
  childSiteId:
    type: integer
    required: true
    displayName: "childSiteId"
    example: 123
  parentSiteId:
    type: integer
    required: true
    displayName: "parentSiteId"
    example: 123
  isActive:
    type: boolean
    displayName: "isActive"
    example: true